### PR TITLE
DEEPLRN-249 adding FastRCNN Soccer example

### PR DESCRIPTION
**Pull request by ChipRobie**
Adds new FastRCNN example using SAS Soccer data. Checked by Doug and Xindian, good to go.

### CODE REVIEW

**Comment by eusdougc** [comment]
This was intended to replace FasterRCNN_Example.ipynb I believe.  The file name is incorrect.

**Comment by ChipRobie** [comment]
No.
This was NOT intended to replace FasterRCNN_Example.ipynb.
It was intended to *supplement* the existing example with one that can be performed by the user. BOTH should be kept.
Not an incorrect file name.
This example was never intended to replace the existing one.
Chip

**Comment by eusdougc** [comment]
@ChipRobie will re-submit the pull request with a different file name.

**Comment by ChipRobie** [comment]
*   @ChipRobie<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FChipRobie&data=04%7C01%7Cchip.robie%40sas.com%7Cc46fad3ea24749b9091708d8803c5950%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637400343972646027%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ml97MK2QPlYjcYBHow97OSDu7MQlqmqGrPxZS6DN3pw%3D&reserved=0> will re-submit the pull request with a different file name.
  *

Done.
Chip

**Pull request closed without merging**
