### PR TITLE
Completely revised

### PR DESCRIPTION
**Pull request by ChipRobie**
- Changed to small data source that users can download
- updated narrative
- added need to run in SMP mode
- addded warnings about size of *.sashdat files
- added code to create vgg16.sashdat file for Model 5
- other edits to change analysis of summmary stats for smaller data set

### CODE REVIEW

**Comment by ChipRobie** [comment]
I put in Ethem's requested changes to A_Comprehensive_Image_Classification_Example notebook on Thursday Feb 13. Anonymized paths, etc.

**Comment by ChipRobie** [comment]
Ethem,
I have made all the changes except your very last one, which I’m not sure I fully understand. Your changes were:


model5.load(path=model_file)
                                             model_file should also include vgg16.sashdat in this setting

If the code block looks like this, are you OK?


model5 = Model(sess)
# The model_file variable holds the fully-qualified server-side path and file name
# for your deployed .sashdat model file.
# This should be the server location where you deployed the 'model3' vgg16.sashdat table.
model_file = '/path-to/server-accessible/deployment-directory/vgg16.sashdat'

# Load the .sashdat file for the stored model.
model5.load(path=model_file)

=Chip

**Comment by ChipRobie** [comment]
Hi Ethem,
I have run the code block you commented on below 11 times in a row with max_display=2. It *always* pulls up the same “random” two images, and the dolphin image *always* has a blank heat map.
How can I fix this? Doing the same thing over and over expecting different results is not working. I think someone once called that the definition of insanity. Can you help?
[cid:image002.jpg@01D5E32F.AC472750]
Chip

**Comment by ethem-kinginthenorth** [comment]
Thanks for the changes.

**Pull request merged**
