### PR TITLE
Edited survival analysis notebook

### PR DESCRIPTION
**Pull request by kybowm**
I made the following changes:
* Edited headings
* Added information about APIs/explained helper functions
* Rearranged some cells - making sure content makes sense and notebook runs end-to-end

### CODE REVIEW

**Comment by ethem-kinginthenorth** [comment]
it is good to me, I requested @AIStatistics also gives a look.

**Comment by AIStatistics** [comment]
The notebook is well organized, and clear. I  polished some markdown to explain survival analysis concepts.

**Comment by kybowm** [comment]
The changes looked good to me. I replaced host/port/path with generics, but otherwise pushed the edits as is.

**Comment by ethem-kinginthenorth** [comment]
looks good to me

**Pull request merged**
