### PR TITLE
EfficientNet for Fruits and Vegetables Image Classification

### PR DESCRIPTION
**Pull request by AIStatistics**

### CODE REVIEW

**Comment by ethem-kinginthenorth** [comment]
@kybowm would you please take a look at this notebook.

@AIStatistics I have only one comment:
[18] would you do log_level=2 so that we dont get everything :)

thanks

**Comment by kybowm** [comment]
I'm not sure the best way to review notebooks on GitHub since they render as static HTML, but here are my suggestions.

1. After running the notebook, open the notebook in a text editor and search/replace the cashost name. Also ensure user and path names are generic.
2. Display is misspelled in section 2.1
3. Generalization is misspelled in section 3.1 bullet point three
4. In the summary on model architecture section, first bullet point: the input dimensions didn't render well. I think backslash will escape the parentheses. 
5. It would be nice if the learning curve plot had a legend or at least a description. Is FitError blue and ValidError orange?
6. A conclusion would be nice. You mentioned that EfficientNet used fewer parameters than ResNet, but does this translate to a training time decrease? Or fewer required training epochs? I'm not suggesting a formal benchmark or anything. If there are some easy conclusions you can make without sending the reader into the EfficientNet paper then they would be great additions.

Everything else looks good. If any of my suggestions are unclear, let me know and I'll try to describe it better.

**Comment by AIStatistics** [comment]
> @kybowm would you please take a look at this notebook.
> 
> @AIStatistics I have only one comment:
> [18] would you do log_level=2 so that we dont get everything :)
> 
> thanks

fixed

**Comment by AIStatistics** [comment]
> I'm not sure the best way to review notebooks on GitHub since they render as static HTML, but here are my suggestions.
> 
> 1. After running the notebook, open the notebook in a text editor and search/replace the cashost name. Also ensure user and path names are generic.
> 2. Display is misspelled in section 2.1
> 3. Generalization is misspelled in section 3.1 bullet point three
> 4. In the summary on model architecture section, first bullet point: the input dimensions didn't render well. I think backslash will escape the parentheses.
> 5. It would be nice if the learning curve plot had a legend or at least a description. Is FitError blue and ValidError orange?
> 6. A conclusion would be nice. You mentioned that EfficientNet used fewer parameters than ResNet, but does this translate to a training time decrease? Or fewer required training epochs? I'm not suggesting a formal benchmark or anything. If there are some easy conclusions you can make without sending the reader into the EfficientNet paper then they would be great additions.
> 
> Everything else looks good. If any of my suggestions are unclear, let me know and I'll try to describe it better.

Revise the notebook with your comments. Thanks!

**Pull request merged**
