### PR TITLE
Update Keras Inception, MNIST, Gen example updates

### PR DESCRIPTION
**Pull request by ChipRobie**
I tested, validated, and updated the notebook examples for python-dlpy/examples/keras_model_conversion/
* KerasModelConversion.jpynb
* Import_Keras_LeNet.jpynb
* Import_InceptionV3_Weights_From_Keras_HDF5.  
The file GeneralModelConversion.jpynb has been recently edited and is good to go. Doug also added a necessary .csv file with weight labels needed by one example.

After ensuring that the example notebooks all had accessible data and could run reliably, I removed my SAS network references and credentials with anonymized stand-in paths.

There are some output cells that contain I/O for Python OS commands that I wish I knew how to delete (SAS network content) without obliterating the entire notebook output, but I don't. Please fix that if there is a way.

### CODE REVIEW

**Comment by eusdougc** [comment]
My comments on Import_Keras_LeNet.ipynb:

- there is inconsistent use of SAS CAS versus SAS Viya in the headings/text.  I believe we are supposed to use SAS Viya.  Can we change all occurrences of SAS CAS accordingly?
- there is a NOTE below cell 9 that indicates the deepLearn action set was loaded but there is no corresponding loadactionset call.  I believe this needs to be removed.
- below cell 11 there is internal path information that need to be anonomized.
- below cell 12 there is CASUSER information that needs to be anonomized (CASUSER(chrobi))

**Comment by eusdougc** [comment]
My only comment on KerasModelConversion.ipynb is that it is somewhat redundant given Import_Keras_LeNet.ipynb.  Do we really need both examples?

**Comment by ChipRobie** [comment]
Hi,
I don’t understand this. Is part of the message missing?
What are the “these two lines”?
If we delete the lines about client and server paths, what is the “something like this” you want added?
You want something deleted and something added, but you only mention one of the two things and I’m not sure which one is what.
Can someone help me understand?
Chip

**Comment by ChipRobie** [comment]
Hi,
I disagree with preferring the term “SAS Viya” over “SAS CAS”. They are not the same thing. SAS CAS is a huge part of SAS Viya but they are not the same or interchangeable terms. We do not have SAS Viya servers, we have SAS CAS servers.  We connect to SAS CAS, not SAS Viya.

Also, I don’t know how to edit or anonymize Jupyter output cells. Who can tell me how?
-Chip

**Comment by ethem-kinginthenorth** [comment]
these_two_lines

**Comment by ChipRobie** [comment]
What is the downside to keeping both? If they are not identical, one of them might be able to teach a feature use or programming construct that the other does not. Since I work through them both, I know I learned from both, even though they have similar content.

In school, math homework always has multiple problems that reinforce how to use a new concept.
Why would we treat programming and usage examples differently? Are we having problems with GitHub space allocation?

Chip

**Comment by ChipRobie** [comment]
When I tested the example, it would not run without loading the action set. Doug said I found a bug.
Just like me when I was testing the code, every reader without the latest DLPy will get an error and the program halts.
Do we assume all DLPy readers are using the very latest release? The resulting error message is not intuitive.
Chip

**Comment by ChipRobie** [comment]
I know I’ve already replied; I don’t feel it’s enough.

For 20+ years, the most frequent, loud, and undiminishing request from SAS customers and doc readers is “WE WANT MORE EXAMPLES!” In 20 years of Pubs booths at SGF, it is *always* the top request. In 20 years of tech support feedback, we have *never* had one complaint about *too many* or redundant examples. Not once ever from customers, only R&D! Readers want more! More!!

Ten years ago I went out on medical leave and Dom on the EM team deleted dozens of doc examples from the EM Help to save build space. The customer outcry was swift and went on for 5 years. We learn by repetition of similar problem solving approaches demonstrated. It’s what Pubs *does*.

For Jiminy Crickets’ sake, unless there is something wrong or broken, two similar examples with different models and data (after they are DONE) is *not* ever a customer problem—it is a bonus. I feel strongly about this.
Chip

**Comment by eusdougc** [comment]
@ChipRobie : Also, I don’t know how to edit or anonymize Jupyter output cells. Who can tell me how?

You have to edit the notebook with a text editor and make the necessary changes.  After saving/exiting, the notebook should be fine.

**Comment by eusdougc** [comment]
@ChipRobie - I know I’ve already replied; I don’t feel it’s enough.

Let's take this conversation off-line

**Comment by ethem-kinginthenorth** [comment]
right client, open as text file, replace all. save.

**Comment by ethem-kinginthenorth** [comment]
@ChipRobie would you please let me know if you have removed the personal info from these examples?

**Comment by ChipRobie** [comment]
Yes. No mention of chrobi or SAS server ids.
Clean and good to go.
Chip

**Pull request merged**
