### PR TITLE
auto-encoder example

### PR DESCRIPTION
**Pull request by chungdz**
Hi, this is the auto-encoder example discussed before.

### CODE REVIEW

**Comment by chungdz** [comment]
@ethem-kinginthenorth I add some comments, fix the bug in cell[5], indent the code snippet in cell[6], and delete the cell[10] and cell[11], for I think they are not necessary.

**Comment by ethem-kinginthenorth** [comment]
thanks

**Comment by eusdougc** [comment]
@chungdz  - there is a problem with the example you provided that was recently discovered by @TimoKettunenSAS.  In cell [8] when the predict function is called, it automatically copies all the data from the input table to the output table.  So the _image_ column in the output table is the _image_ column from the input table.  When you rename this column and then merge back with the input table, you have two copies of the same image.  That is what is displayed in cell [9].

Can you fix the example, or make the data available to us so we can?

**Comment by chungdz** [comment]
@eusdougc Sorry for the mistake. As I no longer have the access to the deeplearning server of DLPY, I'm afraid that I could not fix this problem now. What I can do now is to transfer the data to you so you can revise the cells with flaw. 

I have attached the [image file](https://drive.google.com/file/d/1rrq_ANgw3CWluwoWhLLRWhkOrP85TnLr/view?usp=sharing) for you to download, could you please call me after you download this file successfully? I would like to close the shared link after you finish the downloading.

**Comment by eusdougc** [comment]
Thanks @chungdz .  Please go ahead and close the shared link.  I will use some other images that we can share publicly.

**Pull request merged**
