### PR TITLE
Tested, validated, updated narrative on DLPy_Import_Onnx_Model.jpynb example. 

### PR DESCRIPTION
**Pull request by ChipRobie**
Validated the code and various Python and ONNX library modules used in the code. 
Able to run from end to end. Updated and path-anonymized for DLPy example publication.

### CODE REVIEW

**Comment by ethem-kinginthenorth** [comment]
@yg2288 would you please take a look at to see everything is fine by you.

**Comment by yg2288** [comment]
Looks good to me.  Great work, thanks!

**Comment by ChipRobie** [comment]
Please consider only the most recent PR for today. Adding final changes requested by docair.

**Comment by eusdougc** [comment]
Replaced by pull request #317.

**Pull request closed without merging**
